project_name: dvs

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: "true"
  footer: |
    ## Installation
    ### Linux
    ```
    sudo wget https://github.com/A2-ai/devious/releases/download/{{ .Tag }}/dvs_Linux_x86_64.tar.gz -O /tmp/dvs.tar.gz
    sudo tar xzf /tmp/qvm.tar.gz qvm
    sudo mv qvm /usr/local/bin/qvm
    sudo chmod +x /usr/local/bin/qvm
    ```

    ### Linux (User) 
    Assumes `~/bin` is available in your PATH

    ```
    wget https://github.com/A2-ai/devious/releases/download/{{ .Tag }}/dvs_Linux_x86_64.tar.gz -O /tmp/dvs.tar.gz
    tar xzf /tmp/qvm.tar.gz qvm
    mv qvm ~/bin/qvm
    chmod +x ~/bin/qvm
    ```
